### ISSUE TITLE
Why allocate voxels after optimizing the map？

### ISSUE THREAD

**Issue by lsl-hk** [zju3dv/Vox-Fusion#18]
Hi,
At initialization time, first allocate voxels in the optimized map.
But after initialization,why allocate voxels after optimizing the map?
Every time a new picture comes in, shouldn’t it be allocated voxels first?And then optimize map.
If you don't do that the voxels may not exist on the new surface.
abou this code:
self.do_mapping(share_data, tracked_frame)
self.create_voxels(tracked_frame)

**Comment by garylidd** [comment]
Hi，
Good question. 

The original intention of this design is to prevent the generation of redundant voxels due to the incomplete convergence of the pose of the tracking process. After the joint optimization in mapping process, the pose will be more accurate.
In fact, since the overlap between consecutive frames is relatively large, and our representation can support larger voxel blocks, this does not have much impact in practice.

**Comment by lsl-hk** [comment]
Hi,
Thank you for your answer.I understand it.
