### ISSUE TITLE
Scannet sequence 0000_00 ate value evaluation

### ISSUE THREAD

**Issue by ming82871** [zju3dv/Vox-Fusion#37]
Hi!
Thanks for your excellent work! We use the newest code which you have provided to evaluate the ate results of  sequence_0000 on Scannet dataset. By utilizing the evaluation python file which you have provided, we obtained the ate results 0.15128. The trajectory evaluation figure shows that the estimated pose has some drift conditions. Can you give me some suggestions about experimental detail?

![image](https://user-images.githubusercontent.com/93027401/225848776-1b2585ed-7321-426c-8094-6a8ffaa3a4fd.png)

**Comment by garylidd** [comment]
Hi, 

This may be caused by the running environment, since the coordination of tracking and mapping processes is critical for trajectory accuracy in the case of multiple processes. If the accuracy on your side is not good, you can appropriately increase the number of sampling points and iterations for tracking.
We also provide our results for your reference.
![scene0000](https://user-images.githubusercontent.com/48756786/226074280-7045ca94-8811-4b89-9a61-f108ce434b71.png)
